### ISSUE TITLE
Missing fields in reconstructed Twitter cascade

### ISSUE THREAD

**Issue by liushengzhong1023** [pnnl/socialsim#28]
Hi,

We have been using the cascade reconstruction code you provided to extract the Twitter data for model training. After fixing a few issues locally, we were able to get the extracted data. Our problem now is that we are still missing the **ParentID** for many **retweet** and **quote** events. We have used all the provided Twitter json files under **Crypto**. Have you ever encountered the same issue before? Or have you used it to extract the Twitter data yet?

Thanks,
Shengzhong

**Comment by emily-grace** [comment]
The follower lists for the Crypto and Cyber data sets are only a subsample of the active users in those domains.  The CVE domain is the only where Leidos has collected the followers for all of the users (excluding those where the user was deleted before the follower collection was performed).

Therefore, CVE is the only domain for which we are planning to evaluate Scenario 2 (cascade measurements).  If you download the newest CVE followers data from Leidos, it should be more complete than the crypto followers.  However, there will still be some users missing due to the users who were deleted.  

We will only evaluate on cascades which can be fully reconstructed using the released follower data.  So you can drop any data for which the any of the retweets to the root node are missing the follower information.

For future challenges, we will select users to collect followers based on a sample of cascades rather than a sample of active users.  This will ensure that we can fully reconstruct these selected cascades rather than having followers for only some users in the cascades.

Can you please let us know which issues you fixed locally so we can update the code accordingly?

**Comment by SamTube405** [comment]
@emily-grace What about the retweet chain estimation done by Leidos/ Netanomics, 
1. Are we not supposed to use them in our work?
2. Are you not going to use them for the evaluation?
